//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int id { get; set; }
        public int State_Id { get; set; }
        public int Country_Id { get; set; }
        public string City_Name { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
    }
}
