//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int id { get; set; }
        public Nullable<int> RoomTypeId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public Nullable<int> HotelId { get; set; }
        public Nullable<int> BedId { get; set; }
        public Nullable<int> RoomNumber { get; set; }
        public Nullable<int> RoomStatusId { get; set; }
        public string Description { get; set; }
    
        public virtual Bed Bed { get; set; }
        public virtual Floor Floor { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual Status Status { get; set; }
    }
}
