//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomFacility
    {
        public int id { get; set; }
        public string facilities { get; set; }
        public Nullable<int> Price { get; set; }
        public int floorId { get; set; }
        public string Description { get; set; }
    
        public virtual Floor Floor { get; set; }
    }
}
